Added function to extract nivaport user from headers + api tests #9
create_or_get_user:

Takes base64-encoded json string and parses it into a user object. Then
tries to find user based on user.id. If user does not exist, it inserts
it into the database based on user object object header

This function is not yet used, but is intended to be called with
Niva-User header from requests. Niva-User header is added to requests
when proxied behind niva-port

misc:

- added tests which boots up a postgres instance dedicated for testing.
Wipes all data before each test (custom truncate all function)
  - had some trouble wiping the database with the odm2 user. Using
postgres user instead as a workaround (probably ok for tests?):

```
asyncpg.exceptions.InsufficientPrivilegeError: must be owner of
hypertable "trackresultlocations"
```

TODO: a more proper setup of intial metadata in tests. Just doing 3
ad-hoc inserts now. Need some basic controlled vocabularies++. Just did
this very quickly now
TODO: properly populate affiliations++. Scoped this out for now